### ISSUE TITLE
Linking error on Windows

### ISSUE THREAD

**Issue by kegesch** [sagan-software/eosio-rust#18]
I got this `Link.exe` error on Windows: 

```shell
Creating library C:\<---path-->\contract\target\release\deps\machination.dll.lib and object C:\<---path-->\contract\target\release\deps\machination.dll.exp
          machination.machination.3ct05vdi-cgu.1.rcgu.o : error LNK2019: unresolved external symbol action_data_size referenced in function apply
          machination.machination.3ct05vdi-cgu.1.rcgu.o : error LNK2019: unresolved external symbol read_action_data referenced in function apply
          machination.machination.3ct05vdi-cgu.1.rcgu.o : error LNK2019: unresolved external symbol require_auth referenced in function apply
          machination.machination.3ct05vdi-cgu.1.rcgu.o : error LNK2019: unresolved external symbol current_receiver referenced in function apply
          machination.machination.3ct05vdi-cgu.1.rcgu.o : error LNK2019: unresolved external symbol db_store_i64 referenced in function apply
          machination.machination.3ct05vdi-cgu.1.rcgu.o : error LNK2019: unresolved external symbol db_idx_double_store referenced in function apply
          machination.machination.3ct05vdi-cgu.1.rcgu.o : error LNK2019: unresolved external symbol db_idx64_store referenced in function apply
          machination.machination.3ct05vdi-cgu.1.rcgu.o : error LNK2019: unresolved external symbol db_idx128_store referenced in function apply
          machination.machination.3ct05vdi-cgu.1.rcgu.o : error LNK2019: unresolved external symbol prints_l referenced in function apply
          machination.machination.3ct05vdi-cgu.1.rcgu.o : error LNK2019: unresolved external symbol printn referenced in function apply
          machination.machination.3ct05vdi-cgu.1.rcgu.o : error LNK2019: unresolved external symbol db_find_i64 referenced in function apply
          machination.machination.3ct05vdi-cgu.1.rcgu.o : error LNK2019: unresolved external symbol db_end_i64 referenced in function apply
          machination.machination.3ct05vdi-cgu.1.rcgu.o : error LNK2019: unresolved external symbol db_get_i64 referenced in function apply
          machination.machination.3ct05vdi-cgu.1.rcgu.o : error LNK2019: unresolved external symbol db_update_i64 referenced in function apply
          machination.machination.3ct05vdi-cgu.1.rcgu.o : error LNK2019: unresolved external symbol db_idx64_end referenced in function apply
          machination.machination.3ct05vdi-cgu.1.rcgu.o : error LNK2019: unresolved external symbol db_idx64_find_primary referenced in function apply
          machination.machination.3ct05vdi-cgu.1.rcgu.o : error LNK2019: unresolved external symbol db_idx_double_end referenced in function apply
          machination.machination.3ct05vdi-cgu.1.rcgu.o : error LNK2019: unresolved external symbol db_idx_double_find_primary referenced in function apply
          machination.machination.3ct05vdi-cgu.1.rcgu.o : error LNK2019: unresolved external symbol db_idx_double_update referenced in function apply
          machination.machination.3ct05vdi-cgu.1.rcgu.o : error LNK2019: unresolved external symbol db_idx128_end referenced in function apply
          machination.machination.3ct05vdi-cgu.1.rcgu.o : error LNK2019: unresolved external symbol db_idx128_find_primary referenced in function apply
          machination.machination.3ct05vdi-cgu.1.rcgu.o : error LNK2019: unresolved external symbol db_idx128_update referenced in function apply
          machination.machination.3ct05vdi-cgu.1.rcgu.o : error LNK2019: unresolved external symbol db_idx64_update referenced in function apply
          machination.machination.3ct05vdi-cgu.1.rcgu.o : error LNK2019: unresolved external symbol eosio_assert_message referenced in function _ZN11machination5apply28_$u7b$$u7b$closure$u7d$$u7d$17h8ad46babb3a3f3b6E
          C:\<---path-->\contract\target\release\deps\machination.dll : fatal error LNK1120: 24 unresolved externals
```

This has probably something to do that the `abi!` macro creates an `extern "C" fn`. Do I have to install eosio.cdt SDK for development or how is it linked together?

Versions: 
* Visual Studio 2019
* Rust1.42.0-nightly
* Eosio-rust 0.3.0

**Comment by liamcurry** [comment]
This should be fixed now in master.

**Comment by kegesch** [comment]
Yes works! Thank you.

**Comment by kegesch** [comment]
@liamcurry are you planning to cut a new release? Cargo has a bad time resolving nested git crates.

**Comment by liamcurry** [comment]
@kegesch sure I can work on a `0.3.1` release tonight or tomorrow.

**Comment by liamcurry** [comment]
@kegesch `0.3.1` is released

**Comment by kegesch** [comment]
@liamcurry thank you very much :)
